### ISSUE TITLE
transportDocument.shippingInstructions should include an SI object, not inherit

### ISSUE THREAD

**Issue by nissimsan** [dcsaorg/DCSA-OpenAPI#119]
Calling out data provided in shipping instructions is a great idea (I've applauded this in the past too). But instead of inheriting the properties of shippingInstructions, I suggest you rather just include an actual shippingInstruction object. From a legal standpoint, including the shipper's object is a much clearer distinction of data origin than having the carrier duplicate all its data. 

Here is what I am referring to, I suggest dropping this allOf:
```
          "properties": {
             "shippingInstruction": {
                "allOf": [
                   {
                      "$ref": "#/components/schemas/shippingInstruction"
                   }
                ]
             }
          }
```

**Comment by nissimsan** [comment]
In fact, my comment seems to apply more generically - you're very liberal in your `allOf` usage. 

For example shippingInstructions.cargoItems (copied below) which is also based on an allOf relationship. This means that "shipping instructions is a type of cargo items" - which clearly is nonsense. 

Similarly on the cargoItems-side: cargoItems includes a self-reference to cargoItems. It should just be an array of cargo-elements; there's a "layer" too many, only there to support the above inheritance, but doesn't make "real world" sense. 

```
         "shippingInstruction": {
            "description": "The Shipping Instruction is an enrichment to the original booking shared by the shipper to the carrier. The shipping instruction includes volume or weight, cargo items, shipping dates, origin, destination, and other special instructions. The information given by the shipper through the shipping instruction is the information required to create a Transport Document.",
            "type": "object",
            "allOf": [
               {
                  "$ref": "#/components/schemas/shippingInstructionHeader"
               },
               {
                  "$ref": "#/components/schemas/cargoItems"
               },
               {
                  "$ref": "#/components/schemas/utilizedTransportEquipments"
               },
               {
                  "$ref": "#/components/schemas/documentParties"
               },
               {
                  "$ref": "#/components/schemas/shipmentLocations"
               },
               {
                  "$ref": "#/components/schemas/references"
               }
            ]
         },
         "cargoItems": {
            "type": "object",
            "properties": {
               "cargoItems": {
                  "type": "array",
                  "items": {
                     "$ref": "#/components/schemas/cargoItem"
                  }
               }
            }
         },
```

**Comment by HenrikHL** [comment]
Hi @nissimsan,
Yes - I have been using `allOf` extensively. This has been the best way to "extend" and/or "overwrite" properties in the objects in the specs. If there is a smarter way please let me know...

I don't quite agree with the following statement:

> For example shippingInstructions.cargoItems (copied below) which is also based on an allOf relationship. This means that "shipping instructions is a type of cargo items" - which clearly is nonsense.

`allOf` means that all of the following list of properties should be present. It has nothing to do with the type.

`cargoItems` includes a self-reference to `cargoItem` (without the 's') - appart from that you are right this could probably be defined as an array where needed instead of defining the `cargoItems` object. As I see it the result is the same...

**Comment by nissimsan** [comment]
Hi @HenrikHL 

For anyone looking at the resulting OpenAPI spec, for sure yes: the result is the same! I was digging a step deeper, wanting to leverage your data models underneath which is what led me to this comment. 

We interpret OO inheritance as `allOf` in the CEFACT RDM2API spec (https://edi3.org/specs/edi3-uml-profile/develop/#generalisation-relationship). So I'm wired to treat also consider`allOf` == inheritance (in the opposite direction), but I suppose that might be a slightly old school interpretation on my part. 

Arrays of `cargoItem` defined with simple aggregation where used would have been much easier for me to absorb (for reasons of both technical limitations and convention). But the above points I suppose boil down to modeling preferences - you can't be convinced to change this, can you...?

**Comment by nissimsan** [comment]
... I take that as a silent decline.  :)

**Comment by HenrikHL** [comment]
I will try to take this into account going forward :-)
