### ISSUE TITLE
documentParties?

### ISSUE THREAD

**Issue by nissimsan** [dcsaorg/DCSA-OpenAPI#124]
Hi DCSA,
I'm curious where `documentParties` comes from? Noting that CEFACT spells out party types individually (as opposed to an array with a codification enum parameter). Why the deviation?

**Comment by raisoman** [comment]
Hi @nissimsan

Can you point to the CEFACT model in question?

In DCSA's model, documentParties is the list of parties involved in the shipment, including the role (function) they play.

**Comment by raisoman** [comment]
Closing for now, will reopen if relevant.
