### ISSUE TITLE
Carrier organization information

### ISSUE THREAD

**Issue by nissimsan** [dcsaorg/DCSA-OpenAPI#130]
Hi DCSA, 

I don't see anywhere on the BL/SI schemas for adding basic carrier data, name, address, etc. Seems like an oversight - it's prominent data and always included. 

(Btw, modeling-wise `carrier` could easily be included as a party, but I don't think that's the most correct way to model it).

Cheers

**Comment by nissimsan** [comment]
Well, there is a  carrier element under Transports (pretty deep in the document hierarchy) - is that the intended place to capture the carriers data?

**Comment by raisoman** [comment]
Hi @nissimsan ,

Information about the carrier that characterizes it as a Party will be captured by using the Party Function Code CA (we need to add that in the Swagger spec). The rest (e.g. VSA partnership, vessel ownership etc.) is modelled through the Carrier entity.

Does that make sense?

**Comment by HenrikHL** [comment]
CA (Carrier) has been added to the SwaggerSpecs...

**Comment by nissimsan** [comment]
Seeing it on version 2.0.0. 
A little weird that the Carrier details are specified in the SI, isn't it? But hey - that's not a hill I want to die on.
