### ISSUE TITLE
TNT 2.0 - Inheritance of EventType

### ISSUE THREAD

**Issue by rgenoulaz** [dcsaorg/DCSA-OpenAPI#14]
Hi, 
the overriding eventType property to have correct payload response examples is kinda confusing when it comes to implementation.
It's like having different enum values for the same attribute.

If it's just for examples, I would rather remove the restriction.

**Comment by AsgerStage** [comment]
Hi Romain,

Did you find this to be a problem specifically in regards to codegeneration, or just in general confusing when reading the spec?

Incorrect response payload examples were pointed out long ago, and it was mentioned that that was important that they were correct - so either we would keep it as is, or find another way to display the correct examples. 

I believe the only other way to do this without overriding in this way, would be to manually type each response payload as an example, but that is a lot harder to maintain.

**Comment by rgenoulaz** [comment]
Thank you Asger, you're right, and I remember those discussion.
I understand your statement, however, I think it is more important to keep a clear model even if it brings more complexity in the examples, cause somehow it brings both confusion & code generation issues.
Besides, hopefully examples should not change that often.
