### ISSUE TITLE
CS spec downgraded?

### ISSUE THREAD

**Issue by ilengyel** [dcsaorg/DCSA-OpenAPI#238]
Why was the Commercial Schedules specification downgraded from version 1.0.0 to 1.0.0_Beta1 in PR #185?

The one that is currently on master branch is missing the [cut off](https://github.com/dcsaorg/DCSA-OpenAPI/blob/9aed65ee2b8ab961ef59001e13f84f655faaf391/cs/v1/cs_v1.0.0.yaml#L350C5-L350C11) definitions for PointToPoint schedules.

**Comment by emiliodcsa** [comment]
Hi,

The version you saw "downgraded" wasn't a published version on Swaggerhub. At DCSA, we follow a beta release process, and the initial published API for Commercial Schedules was always intended to be named 1.0.0 Beta 1. The rename from 1.0.0 to 1.0.0 Beta 1 aligns with our publication process. We're currently working on releasing the final version, 1.0.0, and aim to do so by the end of September 2024.

While the branch may be missing some cut-offs, we're reintroducing them for the final version. Further discussions were necessary before their addition.

Hope this clarifies things.

Emilio.

**Comment by ilengyel** [comment]
Yep it did, thanks.

**Comment by emiliodcsa** [comment]
> Why was the Commercial Schedules specification downgraded from version 1.0.0 to 1.0.0_Beta1 in PR #185?
> 
> The one that is currently on master branch is missing the [cut off](https://github.com/dcsaorg/DCSA-OpenAPI/blob/9aed65ee2b8ab961ef59001e13f84f655faaf391/cs/v1/cs_v1.0.0.yaml#L350C5-L350C11) definitions for PointToPoint schedules.



> Yep it did, thanks.

Hi, we have updated the API Specifications and change log. You can find it here: https://app.swaggerhub.com/apis/dcsaorg/DCSA_CS/1.0.0
https://github.com/dcsaorg/DCSA-OpenAPI/tree/master/cs/v1

Expect to have them published on Sept 24th.
