### ISSUE TITLE
pub/sub

### ISSUE THREAD

**Issue by rlilov** [dcsaorg/DCSA-OpenAPI#5]
Looking at OpenApi  specs as published on SwaggerHub https://app.swaggerhub.com/apis/dcsaorg/DCSA_OAS/1.0.0#/Events/get_events, looks like only GET method is implemented. If event providers (carriers) are to implement this specs, they are running the risk of being inundated with GET requests, or having to subject them to quota, that will effectively decrease the perceived value of their API offering .

Current EDI approach, where event receiver acts as a subscriber and event provider (carrier) acts as publisher and pushes new events as they become available (via FTP, AS2) seems to be more practical.

Are you considering publishing pub/sub endpoints , where API consumer can subscribe for BN, BL and carrier can post to customer URL (aka webhook), with recommended and documented retry logic?

I believe if this is done, adoption of this API may increase.

**Comment by AsgerStage** [comment]
Hi Rlilov,

Thanks for your question.

We are working on a subscription endpoint as we speak, and plan to have it included in one of the next two releases.

Let me know if you have any more questions :)

Regards
Asger
